apiVersion: v1
kind: ConfigMap
metadata:
  name: jukebox0-config
  labels:
    app.kubernetes.io/name: jukebox0
data:
  INTERACTIVE_KEY: '2DC31TyqSLIls6VGdF8t'
  PORT: '3000'
  INSTANCE_DOMAIN: 'api.topia.io'
  NODE_ENV: 'production'
  SAFE_SEARCH: 'strict'
  REDIS_URL: 'rediss://topia-dev-sdk-apps-internal-l7mqm2.serverless.use1.cache.amazonaws.com:6379'
